# Generated by Django 3.0.8 on 2020-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=1000)),
                ('media_type', models.CharField(choices=[('MP4', 'Mp4'), ('MP3', 'Mp3'), ('MKV', 'Mkv'), ('AVI', 'Avi'), ('TS', 'Ts')], max_length=5)),
            ],
        ),
    ]
